### ISSUE TITLE
Support gosec checks

### ISSUE THREAD

**Issue by sc250024** [dnephin/pre-commit-golang#46]
# Description

While doing some source code analysis for my M.Sc., I ran across this tool `gosec`: https://github.com/securego/gosec.

Would be cool if this repository supports checking with `gosec`. I'll probably spin up a PR later for it.

**Comment by dnephin** [comment]
Instead of adding all the linters individually I think it might be easier to use the [golangci-lint hook](https://github.com/dnephin/pre-commit-golang/blob/master/run-golangci-lint.sh). `gosec` is one of the supported linters: https://golangci-lint.run/usage/linters/

You could create a `.golangci.yml` with uses `disable-all: true`, and then only enables `gosec` to have it run only that one linter.

**Comment by sc250024** [comment]
Ah good point. Nevermind.
